# 1. Base Line (mean preediction)
# 2. Data cleaning & preparation
# 3. Linear regession model
# 4. Feature Engg.
# 5. Tunning
# 6. Cross Validation
# 7. Residual Analysis

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
data = {
    'StudyHours': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Attendance': [60, 65, 70, 72, 75, 80, 85, 88, 90],
    'PrevScore': [40, 45, 50, 55, 60, 65, 70, 75, 80],
    'FinalMarks': [50, 55, 60, 65, 70, 75, 78, 85, 88]
}

df=pd.DataFrame(data)
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [3]:
y=df['FinalMarks']
y

0    50
1    55
2    60
3    65
4    70
5    75
6    78
7    85
8    88
Name: FinalMarks, dtype: int64

In [4]:
y_pred_baseline=np.repeat(y.mean(), len(y))

In [5]:
mae=mean_absolute_error(y,y_pred_baseline)
print(mae)

10.716049382716049

In [6]:
mse=mean_squared_error(y,y_pred_baseline)
print(mse)

154.02469135802468

In [7]:
rmse=np.sqrt(mse)
print(rmse)

12.410668449282847

In [8]:
r2= r2_score(y,y_pred_baseline)
print(f'Baseline MAE={mae:.2f}, RMSE{rmse:.2f}, R-Squared={r2:.2f}')

Baseline MAE=10.72, RMSE12.41, R-Squared=0.00

In [9]:
# Clean the data
print(df.isnull().sum())

StudyHours    0
Attendance    0
PrevScore     0
FinalMarks    0
dtype: int64

In [10]:
df=df.fillna(df.mean())

In [11]:
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [12]:
# Data prep, find imput, output
X=df[['StudyHours','Attendance','PrevScore']]
y=df['FinalMarks']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [13]:
# model creation
model=LinearRegression()

In [14]:
# train the model
model.fit(X_train,y_train)

LinearRegression()

In [15]:
print('Original Final Marks')
print(y)
y_all_prediction=model.predict(X)
print('Predicted all final Marks')
print(y_all_prediction)

Original Final Marks
0    50
1    55
2    60
3    65
4    70
5    75
6    78
7    85
8    88
Name: FinalMarks, dtype: int64
Predicted all final Marks
[50.65945946 55.16756757 59.67567568 64.62162162 69.42162162 73.92972973
 78.43783784 83.23783784 88.18378378]

In [16]:
y_pred=model.predict(X_test)
print(y_pred)

[83.23783784 55.16756757 73.92972973]

In [17]:
mae=mean_absolute_error(y_test,y_pred)
print(mae)

0.9999999999999906

In [18]:
mse=mean_squared_error(y_test,y_pred)
print(mse)

1.426257608960287

In [19]:
rmse=np.sqrt(mse)
print(rmse)

1.1942602768912174

In [20]:
r2=r2_score(y_test,y_pred)
print(r2)

0.9908312010852554

In [21]:
print(f'Baseline MAE={mae:.2f}, RMSE{rmse:.2f}, R-Squared={r2:.2f}')

Baseline MAE=1.00, RMSE1.19, R-Squared=0.99

# Exercise assignment
# Base line (mean prediction)
2. Data Cleaning & preparation
3. Linear Regression Model
4. Find oout MAE, RMSE,R-Squared
5. Data set as follows:

data = {
    'Area': [850, 900, 1000, 1100, 1200, 1500,1600, 1800, 2000],
    'Bedrooms': [1, 2, 2, 2, 3, 3, 2, 4, 4],
    'Age': [1, 1, 3, 2, 1, 2, 2, 1, 2],
    'PriceIn100K': [5, 6, 7, 7, 70, 9, 9, 11, None]
}

In [22]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.tree import DecisionTreeRegressor

In [23]:
data = {
    'Area': [850, 900, 1000, 1100, 1200, 1500, 1600, 1800, 2000],
    'Bedrooms': [1, 2, 2, 2, 3, 3, 2, 4, 4],
    'Age': [1, 1, 3, 2, 1, 2, 2, 1, 2],
    'PriceIn100K': [5, 6, 7, 7, 7, 9, 9, 11, 7.]}

In [24]:
df = pd.DataFrame(data)

In [25]:
X = df[['Area', 'Bedrooms', 'Age']]
y = df['PriceIn100K']

In [26]:
dt_model = DecisionTreeRegressor(min_samples_leaf=2, random_state=42)

In [27]:
dt_model.fit(X, y)

DecisionTreeRegressor(min_samples_leaf=2, random_state=42)

In [28]:
y_pred = dt_model.predict(X)

In [29]:
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y, y_pred)

print("--- Model Performance (min_samples_leaf=2) ---")
print(f'R-Squared (R2) = {r2:.2f}')
print(f'MAE = {mae:.2f}')
print(f'RMSE = {rmse:.2f}')

--- Model Performance (min_samples_leaf=2) ---
R-Squared (R2) = 0.68
MAE = 0.56
RMSE = 0.97